default:
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker --version
    - echo -e "\033[1;36m DO_RELEASE:$DO_RELEASE RELEASE_IMAGE:$RELEASE_IMAGE WITH_CACHE:$WITH_CACHE \033[0;37m"
    - echo -e "\033[1;36m DRUPAL_CURRENT:$DRUPAL_CURRENT DRUPAL_TRANSITION:$DRUPAL_TRANSITION DRUPAL_DEV:$DRUPAL_DEV \033[0;37m"
    # Pull base image from Docker hub.
    - docker pull --quiet $IMAGE_BASE || true
    - if [ ! $EXTRA_IMAGE == 0 ]; then docker pull --quiet $EXTRA_IMAGE || true; fi
    # Login to Gitlab and pull current image if exist.
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - echo -e "\033[1;36m Pull $CI_REGISTRY_IMAGE/$IMAGE \033[0;37m"
    - docker pull --quiet $CI_REGISTRY_IMAGE/$IMAGE || true
  artifacts:
    paths:
      - report.xml
    reports:
      junit: report.xml

stages:
  # Base image is without drupal.
  - base
  - drupal

variables:
  DRUPAL_CURRENT: '8.8'
  DRUPAL_TRANSITION: '8.9'
  DRUPAL_DEV: '9.0'
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER
  DO_RELEASE: 1
  # Cache seems too hard...
  WITH_CACHE: 0
  SKIP_TESTS: 0
  EXTRA_IMAGE: 0

.build_test_release:
  script:
    # Make sure we are using Gitlab image as base and not docker hub (will do nothing for base).
    - sed -i "s#FROM mogtofu33/drupal8ci#FROM ${CI_REGISTRY_IMAGE}/drupal8ci#g" ${CI_PROJECT_DIR}/$DIR/Dockerfile
    # Build the image.
    - echo -e "\033[1;36m Build $CI_REGISTRY_IMAGE/$IMAGE from $DIR \033[0;37m"
    - |
      if [ $WITH_CACHE == 1 ]; then
        docker build --compress --cache-from $CI_REGISTRY_IMAGE/$IMAGE --tag $CI_REGISTRY_IMAGE/$IMAGE $DIR
      else
        docker build --compress --tag $CI_REGISTRY_IMAGE/$IMAGE $DIR
      fi
    - docker images
    # Tests
    - |
      if [ $SKIP_TESTS == 0 ]; then
        echo -e "\033[1;36m Run $CI_REGISTRY_IMAGE/$IMAGE /scripts/run-tests.sh report \033[0;37m"
        docker run --rm -t $CI_REGISTRY_IMAGE/$IMAGE /scripts/run-tests.sh report > report.xml
      fi
    - echo -e "\033[1;36m Push $CI_REGISTRY_IMAGE/$IMAGE \033[0;37m"
    # Push to Gitlab registry for next steps.
    - docker push $CI_REGISTRY_IMAGE/$IMAGE
  after_script:
    - docker tag $CI_REGISTRY_IMAGE/$IMAGE $RELEASE_IMAGE/$IMAGE
    - docker images
    # Login to Docker hub, tag and push.
    - |
      if [ $DO_RELEASE == 1 ]; then
        echo -e "\033[1;36m Push $RELEASE_IMAGE/$IMAGE to $RELEASE_REGISTRY with user $RELEASE_USER \033[0;37m"
        docker login -u $RELEASE_USER -p $RELEASE_PASSWORD $RELEASE_REGISTRY
        docker push $RELEASE_IMAGE/$IMAGE
      fi

base:
  stage: base
  extends: .build_test_release
  variables:
    # Format is for Gitlab ci for Drupal: drupal8ci:${CI_REF}-${CI_DRUPAL_VERSION}
    IMAGE: drupal8ci:${CI_COMMIT_BRANCH}-base
    DIR: '${DRUPAL_CURRENT}/base'
    # Base official image.
    IMAGE_BASE: drupal:${DRUPAL_CURRENT}-apache
    EXTRA_IMAGE: composer:latest

current:$DRUPAL_CURRENT:
  stage: drupal
  dependencies:
    - base
  extends: .build_test_release
  variables:
    IMAGE_BASE: ${CI_REGISTRY_IMAGE}/drupal8ci:${CI_COMMIT_BRANCH}-base
    IMAGE: drupal8ci:${CI_COMMIT_BRANCH}-${DRUPAL_CURRENT}
    DIR: '${DRUPAL_CURRENT}/drupal'

transition:$DRUPAL_TRANSITION:
  stage: drupal
  dependencies:
    - base
  extends: .build_test_release
  variables:
    IMAGE_BASE: ${CI_REGISTRY_IMAGE}/drupal8ci:${CI_COMMIT_BRANCH}-base
    IMAGE: drupal8ci:${CI_COMMIT_BRANCH}-${DRUPAL_TRANSITION}
    DIR: '${DRUPAL_TRANSITION}/drupal'

dev:$DRUPAL_DEV:
  stage: drupal
  dependencies:
    - base
  extends: .build_test_release
  variables:
    IMAGE_BASE: ${CI_REGISTRY_IMAGE}/drupal8ci:${CI_COMMIT_BRANCH}-base
    IMAGE: drupal8ci:${CI_COMMIT_BRANCH}-${DRUPAL_DEV}
    DIR: '${DRUPAL_DEV}/drupal'
